version: '3'

services:
  web:
    image: wordpress:6.4-php8.1-apache
    restart: always
    volumes: [
      './wp-content:/var/www/html/wp-content',
      './wordpress:/var/www/html',
    ]
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: my-wpdb
    ports:
      - "8080:80"
    networks:
      - wp-network

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    networks:
      - wp-network

  mysql:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my-wpdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: password
    networks:
      - wp-network

  # cli:
  #   image: wordpress:cli-2.8-php8.0
  #   restart: always
  #   volumes: ['./:/var/www/html/']  
  #   working_dir: /var/www/html
  #   networks:
  #     - wp-network

networks:
  wp-network:
    driver: bridge
    
volumes: 
  db_data:
